site_name: ElektraLibra
site_description: Elektronik komponentler icin teknik bilgi kutuphanesi
site_author: ElektraLib
site_url: https://elektralib.github.io/ElektraLibra/
repo_url: https://github.com/ElektraLib/ElektraLibra
repo_name: ElektraLib/ElektraLibra

theme:
  name: material
  language: tr
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Karanlik moda gec
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Aydinlik moda gec
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search:
      lang: tr

nav:
  - Ana Sayfa: index.md
  - Komponentler:
      - Guc Yonetimi:
          - TPS5420D: components/tps5420d.md

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
